name: 手动触发的工作流程

on:
  workflow_dispatch:
    inputs:
      custom_param:
        description: 自定义参数
        required: true

env:
  LAF_APPID: ${{ secrets.HYSLI_API_TEST_APPID }}
  LAF_PAT: ${{ secrets.HYSLI_API_TEST_PAT }}
  API_URL: ${{ secrets.HYSLI_API_TEST_URL }}

jobs:
   publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
          registry-url: https://registry.npmjs.org/
        # 安装 laf-cli
      - name: Install Laf-CLI
        run: |
          npm install -g nw-laf-cli@latest -y
          laf -v
          mkdir laf-cloud
        # 登录 laf api 并初始化
      - name: Login laf-cli
        working-directory: laf-cloud
        run: |
          laf user add ${{ env.LAF_APPID }} -r ${{ env.API_URL }}
          laf user switch ${{ env.LAF_APPID }}
          laf login $LAF_PAT
          laf app init ${{ env.LAF_APPID }}
        # 发布推送的云函数代码推送到指定的 Laf 应用，只有合并成功的代码才会发布
      - name: Depoy Laf Functions
        working-directory: laf-cloud
        run: |
          laf db export ./
          ls
