name: 手动触发的工作流程

on:
  workflow_dispatch:
    inputs:
      custom_param:
        description: 自定义参数
        required: true

jobs:
  http-request:
    runs-on: ubuntu-latest

    steps:
      - name: 执行手动触发的操作
        run: echo "执行手动触发的操作，自定义参数为 ${{ github.event.inputs.custom_param }}"
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Send HTTP request
        run: node send-request.js ${{ github.event.inputs.custom_param }}"
