name: 自动备份数据库

on:
  workflow_dispatch:

env:
  LAF_APPID: ${{ secrets.LAF_APPID }}
  LAF_PAT: ${{ secrets.LAF_PAT }}
  API_URL: ${{ secrets.API_URL }}
  STORAGE_NAME: ${{ secrets.STORAGE_NAME }}

jobs:
   publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
          registry-url: https://registry.npmjs.org/
        # 安装 laf-cli
      - name: Install Laf-CLI
        run: |
          npm install -g nw-laf-cli@latest -y
          laf -v
          mkdir laf-cloud
        # 登录 laf api 并初始化
      - name: Login laf-cli
        working-directory: laf-cloud
        run: |
          laf user add $LAF_APPID -r $API_URL
          laf user switch $LAF_APPID
          laf login $LAF_PAT
          laf app init $LAF_APPID
        # 发布推送的云函数代码推送到指定的 Laf 应用，只有合并成功的代码才会发布
      - name: 获取当前时间
        env:
          TZ: Asia/Shanghai
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M-%S')"
      - name: 备份数据到云存储
        working-directory: laf-cloud
        run: |
          laf db export ./
          mkdir db
          mv $LAF_APPID-db.gz db/${{ steps.date.outputs.today }}-db.gz
          laf storage push $STORAGE_NAME db
